-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:
-- 

-- List the number of films per category.
SELECT COUNT(f.film_id) AS total_films, c.name AS category_name
FROM film AS f
JOIN film_category as fc ON fc.film_id = f.film_id
JOIN category AS c ON c.category_id =  fc.category_id
GROUP BY category_name;

-- Retrieve the store ID, city, and country for each store.

-- store store_id address_id
-- address address_id city_id
-- city city_id county_id
-- country county_id

SELECT 
    s.store_id,
    ci.city,
    co.country
FROM 
    store AS s
JOIN 
    address AS a ON s.address_id = a.address_id
JOIN 
    city AS ci ON a.city_id = ci.city_id
JOIN 
    country AS co ON ci.country_id = co.country_id;

-- Calculate the total revenue generated by each store in dollars.

-- store manager_staff_id
-- staff store_id staff_id
-- payment staff_id amount
 
SELECT 
    s.store_id AS store_name,
    FORMAT(SUM(p.amount), 2, 'en_US') AS Total_revenue
FROM 
    store AS s
JOIN 
    staff AS st ON s.store_id = st.store_id
JOIN 
    payment AS p ON p.staff_id = st.staff_id
GROUP BY s.store_id
;
    
-- Determine the average running time of films for each category.

SELECT 
		
		floor(avg(length) / 60) as hours,
		round( (avg(length) % 60 ), 0) as minutes,
		c.name AS category_name
		
FROM film AS f
JOIN film_category as fc ON fc.film_id = f.film_id
JOIN category AS c ON c.category_id =  fc.category_id
GROUP BY category_name;



-- Bonus:
-- 
-- Identify the film categories with the longest average running time.
SELECT 
		
		floor(avg(length) / 60) as hours,
		round( (avg(length) % 60 ), 0) as minutes,
		c.name AS category_name
		
FROM film AS f
JOIN film_category as fc ON fc.film_id = f.film_id
JOIN category AS c ON c.category_id =  fc.category_id
GROUP BY category_name
ORDER BY AVG(f.length) DESC
LIMIT 1;


-- Display the top 10 most frequently rented movies in descending order.

SELECT 
    f.title AS film_title,
    COUNT(r.rental_id) AS rental_count
FROM 
    rental AS r
JOIN 
    inventory AS i ON r.inventory_id = i.inventory_id
JOIN 
    film AS f ON i.film_id = f.film_id
GROUP BY 
    f.title
ORDER BY 
    rental_count DESC
LIMIT 10;

-- Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT count(i.inventory_id) AS avaliable
FROM inventory i
JOIN film f ON i.film_id = f.film_id
LEFT JOIN rental r ON i.inventory_id = r.inventory_id AND r.return_date IS NULL
WHERE f.title = 'Academy Dinosaur' AND i.store_id = 1;



-- ( Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- 	Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, 
-- 	and this information can be obtained using a CASE statement combined with IFNULL." )

SELECT 
    f.title AS film_title,
    CASE 
        WHEN IFNULL(i.inventory_id, 0) = 0 THEN 'NOT available'
        ELSE 'Available'
    END AS availability_status
FROM 
    film AS f
LEFT JOIN 
    inventory AS i ON f.film_id = i.film_id
ORDER BY 
    film_title;



-- Here are some tips to help you successfully complete the lab:
-- 
-- Tip 1: This lab involves joins with multiple tables, which can be challenging. Take your time and follow the steps we discussed in class:
-- 
-- Make sure you understand the relationships between the tables in the database. 
-- This will help you determine which tables to join and which columns to use in your joins.
-- Identify a common column for both tables to use in the ON section of the join. 
-- If there isn't a common column, you may need to add another table with a common column.
-- Decide which table you want to use as the left table (immediately after FROM) and which will be the right table (immediately after JOIN).
-- Determine which table you want to include all records from. This will help you decide which type of JOIN to use. 
-- If you want all records from the first table, use a LEFT JOIN. If you want all records from the second table, use a RIGHT JOIN. 
-- If you want records from both tables only where there is a match, use an INNER JOIN.
-- Use table aliases to make your queries easier to read and understand. This is especially important when working with multiple tables.
-- Write the query
-- Tip 2: Break down the problem into smaller, more manageable parts. For example, 
-- you might start by writing a query to retrieve data from just two tables before adding additional tables to the join. 
-- Test your queries as you go, and check the output carefully to make sure it matches what you expect. 
-- This process takes time, so be patient and go step by step to build your query incrementally.